### ISSUE TITLE
Tasks to complete

### ISSUE THREAD

**Issue by sirateek** [sirateek/SSD-Lab8#1]
- [x]  Add colors for different numbers
- [x]  Add gui to show a number of remaining flags. A player can't put flags more than what they have.
- [x] Add a logic to check if player wins the game. A player wins when all cells that don't contain mines are revealed.
- [x] Add a restart button.

**Comment by vitvara** [comment]
Add a restart button.
Can someone fix this bug please I don't know what to do now.
First start up
<img width="451" alt="image" src="https://user-images.githubusercontent.com/69972884/162560400-d5293b2c-2636-402f-a116-c405e453d4b5.png">
When mouse pass by
<img width="448" alt="image" src="https://user-images.githubusercontent.com/69972884/162560395-36c4049c-c493-4c53-836a-a02ab011baf6.png">
when playing
<img width="455" alt="image" src="https://user-images.githubusercontent.com/69972884/162560404-e43ef71c-750a-4f22-80e7-f1644150376e.png">

I think it is about z index but I don't know how to fix it. :(

**Comment by sirateek** [comment]
@vitvara 
Fixed in [7fd6df0](https://github.com/sirateek/SSD-Lab8/commit/7fd6df0d9826ce40b457e9b1b18cd8237c838695)
Simply use remove the box color and the button is shown up.

**Comment by sirateek** [comment]
All tasks are done.
So I'm closing this now. :)
